# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('writer', models.CharField(max_length=50, verbose_name='\u4f5c\u8005')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
                ('content', models.TextField()),
                ('is_show', models.BooleanField()),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
